export const cartTypes = Object.freeze({
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  RESET: 'RESET',
  REMOVE: 'REMOVE',
  CLEAR_CART: 'CLEAR_CART',
  GET_TOTALS: 'GET_TOTALS',
  TOGGLE_AMOUNT: 'TOGGLE_AMOUNT',
});
